package marker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	Start         = "<!-- dircard:start -->"
	End           = "<!-- dircard:end-->"
	GeneratedText = "This section was automatically generated by `dircard init`.\nPlease edit the content as needed."
)

type Action string

const (
	ActionCreated  Action = "created"
	ActionAppended Action = "appended"
	ActionUpdated  Action = "updated"
)

func IsReadme(path string) bool {
	bn := filepath.Base(path)
	return bn == "README" || bn == "README.md"
}

func Contains(s string) bool {
	return strings.Contains(s, Start) && strings.Contains(s, End)
}

func AppendIfNeeded(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if Contains(string(data)) {
		return nil
	}

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_APPEND, 0)
	if err != nil {
		return err
	}
	defer f.Close()

	block := "\n" + Start + "\n" + GeneratedText + "\n" + End + "\n"
	_, err = f.WriteString(block)
	return err
}

// InitialContent returns initial file content; README files include dircard markers.
func InitialContent(path string) []byte {
	if IsReadme(path) {
		return []byte("# README\n\n" + Start + "\n" + GeneratedText + "\n" + End + "\n")
	}

	fileName := filepath.Base(path)
	return []byte("# " + fileName + "\n\nAdd notes for this directory.\n")
}

// CreateOrUpdate creates the file, overwrites it, or appends markers (README only)
// depending on whether it exists and whether force is set.
func CreateOrUpdate(path string, force bool) (Action, error) {
	if _, err := os.Stat(path); err == nil {
		if !force {
			if IsReadme(path) {
				return "", fmt.Errorf("%s already exists, use --force to append markers", path)
			}
			return "", fmt.Errorf("%s already exists, use --force to overwrite", path)
		}
		if IsReadme(path) {
			if err := AppendIfNeeded(path); err != nil {
				return "", err
			}
			return ActionAppended, nil
		}
		if err := os.WriteFile(path, InitialContent(path), 0644); err != nil {
			return "", err
		}
		return ActionUpdated, nil
	} else if !os.IsNotExist(err) {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, InitialContent(path), 0644); err != nil {
		return "", err
	}
	return ActionCreated, nil
}
